apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-tester
spec:
  selector:
    matchLabels:
      app: network-tester
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: network-tester
    spec:
      containers:
        - image: quay.io/leroyshirto/network-tester:latest
          name: network-tester
          ports:
            - name: ingress
              containerPort: 5000
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: 700m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 150Mi
      terminationGracePeriodSeconds: 10
