apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - deploy.yaml
  - svc.yaml
images:
  - name: network-tester
    newName: quay.io/leroyshirto/network-tester
    newTag: latest
